---
- name: Build PBS Pro Execution
  hosts: compute
  become: true
  user: opc

  tasks:
    - name: unzip PBS Pro 19.1.3
      unarchive:
       src: https://github.com/openpbs/openpbs/releases/download/v19.1.3/pbspro_19.1.3.centos_7.zip
       dest: /home/opc
       remote_src: yes

    - name: Install PBS Pro Execution node
      yum:
        name: /home/opc/pbspro_19.1.3.centos_7/pbspro-execution-19.1.3-0.x86_64.rpm
        state: present

    - name: modify /etc/pbs.conf
      lineinfile: >-
        dest='/etc/pbs.conf'
        state=present
        backrefs=yes
        regexp='CHANGE_THIS_TO_PBS_PRO_SERVER_HOSTNAME'
        line='PBS_SERVER=bastion'

    - name: modify /var/spool/pbs/mom_priv/config
      lineinfile: >-
        dest='/var/spool/pbs/mom_priv/config'
        state=present
        backrefs=yes
        regexp='CHANGE_THIS_TO_PBS_PRO_SERVER_HOSTNAME'
        line='$clienthost bastion'

    - name: start PBS Pro Execution
      systemd:
         name: pbs.service
         state: started
         enabled: yes
