---
- name: Build PBS Pro Server
  hosts: pbsserver
  sudo: yes
  user: opc

  tasks:
    - name: unzip PBS Pro 19.1.3
      unarchive:
       src: https://github.com/openpbs/openpbs/releases/download/v19.1.3/pbspro_19.1.3.centos_7.zip
       dest: /home/opc
       remote_src: yes

    - name: Install PBS Pro Server
      yum:
        name: /home/opc/pbspro_19.1.3.centos_7/pbspro-server-19.1.3-0.x86_64.rpm
        state: present

    - name: start PBS Server
      systemd:
         name: pbs.service
         state: started
         enabled: yes
